=== Manuelrg99/LLMM/Validación/consola.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="consolas">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="consola">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="plataforma" type="xs:string"/>
            <xs:element name="version" type="xs:integer"/>
            <xs:element name="juegos">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="accion">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="rol">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="arcade">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>

                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="fecha_lanzamiento" type="xs:date"/>
            <xs:element name="exito">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="ventas">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="numero" type="xs:integer"/>
                        <xs:element name="mes" type="xs:string"/>
                        <xs:element name="anno" type="xs:integer"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="plataforma" type="xs:string"/>
            <xs:element name="version" type="xs:integer"/>
            <xs:element name="juegos">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="accion">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="rol">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="arcade">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="fecha_lanzamiento" type="xs:date"/>
            <xs:element name="exito">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="ventas">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="numero" type="xs:integer"/>
                        <xs:element name="mes" type="xs:string"/>
                        <xs:element name="anno" type="xs:integer"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="plataforma" type="xs:string"/>
            <xs:element name="version" type="xs:integer"/>
            <xs:element name="juegos">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="accion">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="rol">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="arcade">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="fecha_lanzamiento" type="xs:string"/>
            <xs:element name="exito">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="ventas">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="numero" type="xs:integer"/>
                        <xs:element name="mes" type="xs:string"/>
                        <xs:element name="anno" type="xs:integer"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Manuelrg99/LLMM/Validación/consola.xml
<?xml version="1.0"?>
<consolas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="consola.xsd">
    <consola>
        <plataforma>PS</plataforma>
        <version>4</version>
            <juegos>
                <accion>
                    <nombre>Juego 1</nombre>
                </accion>
                <rol>
                    <nombre>Juego 1</nombre>
                </rol>
                <arcade>
                    <nombre>Juego 1</nombre>
                </arcade>
            </juegos>
                <fecha_lanzamiento>2020-10-10</fecha_lanzamiento>
                <exito>
                    <ventas>
                        <numero>300</numero>
                        <mes>Enero</mes>
                        <anno>2022</anno>
                    </ventas>
                </exito>
        <plataforma>PS</plataforma>
            <version>5</version>
                <juegos>
                    <accion>
                        <nombre>Juego 1</nombre>
                    </accion>
                    <rol>
                        <nombre>Juego 1</nombre>
                    </rol>
                    <arcade>
                        <nombre>Juego 1</nombre>
                    </arcade>
                </juegos>
                <fecha_lanzamiento>2021-10-10</fecha_lanzamiento>
                    <exito>
                        <ventas>
                            <numero>600</numero>
                            <mes>Enero</mes>
                            <anno>2022</anno>
                        </ventas>
                    </exito>
        <plataforma>XBOX</plataforma>
            <version>2021</version>
                <juegos>
                    <accion>
                        <nombre>Juego 1</nombre>
                    </accion>
                    <rol>
                        <nombre>Juego 1</nombre>
                    </rol>
                    <arcade>
                        <nombre>Juego 1</nombre>
                    </arcade>
                </juegos>
                <fecha_lanzamiento>2019-10-10</fecha_lanzamiento>
                <exito>
                    <ventas>
                        <numero>1000</numero>
                        <mes>Enero</mes>
                        <anno>2022</anno>
                    </ventas>
                </exito>
    </consola>
</consolas>
