=== Manuelrg99/LLMM/Validación/XSD/Calendario/Calendario.xsd
<?xsd version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Calendario">
    <xs:complexType>
        <xs:sequence>
            
            <xs:element name="trimestre">
                <xs:complexType>
                    <xs:sequence>


                        <xs:element name="asignatura" minOccurs="1" maxOccurs="6">
                            <xs:complexType>
                                <xs:sequence>


                                    <xs:element ref="tema">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="nombre" type="xs:string"/>
                                                <xs:element name="notamedia" minOccurs="1" maxOccurs="10">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="teoria" type="xs:float"/>
                                                            <xs:element name="practica" type="xs:float"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>

                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="tema">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
        
            <xs:element name="notaMedia" type="string"></xs:element>
        
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
</xs:element>






</xs:schema>

=== Manuelrg99/LLMM/Validación/Calendario.xml
<?xml version="1.0"?>
<Calendario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Calendario.xsd">
    <trimestre atributo="primero">
        <asignatura nombre="LLMM" min="1" max="6">
            <tema id="4" min="1" max="10">
                <nombre>RSS</nombre>
                <nota_media>
                    <teoria>8.5</teoria>
                    <teoria>7</teoria>
                    <practica>9.5</practica>
                    <practica>8</practica>
                </nota_media>
            </tema>
            <fecha_Examenes>20-10-2021</fecha_Examenes>
        </asignatura>
    </trimestre>








</Calendario>

=== Manuelrg99/LLMM/Validación/XSD/Calendario/Calendario.xml
<?xml version="1.0"?>
<Calendario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Calendario.xsd">
<trimestre ciclos="primero">
    <asignatura nombre="LLMM">
        <tema id="4">
            <nombre>RSS</nombre>
            <notamedia>
                <teoria>8.5</teoria>
                <teoria>7</teoria>
            </notamedia>
            <notamedia>
                <practica>9.5</practica>
                <practica>8</practica>
            </notamedia>
        </tema>
        <tema id="5">
            <nombre>RSS</nombre>
            <notamedia>
                <teoria>8.5</teoria>
                <teoria>7</teoria>
            </notamedia>
            <notamedia>
                <practica>9.5</practica>
                <practica>8</practica>
            </notamedia>
        </tema>
        
        <fecha_Examenes>20-10-2021</fecha_Examenes>
        <fecha_Examenes>20-10-2021</fecha_Examenes>
        <fecha_Examenes>20-10-2021</fecha_Examenes>
    </asignatura>
</trimestre>
</Calendario>
