=== Manuelrg99/LLMM/Validación/XSD/ejercicios/ejercicios.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ejercicios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numero">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:pattern value="[+][0-9]{11}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="password">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="5"/>
              <xs:maxLength value="8"/>
              <xs:pattern value="[a-zA-Z0-9]*"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="dni">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9]{8}[-][a-zA-Z]"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
          
        <xs:element name="correo">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="100"/>
                    <xs:pattern value="[_]*[a-z0-9]{6,50}[@][a-z]{1,10}[.][a-z]{2,6}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>

        <xs:element name="coincidencia">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="tontería|maldito|caray|caramba|madre mía|ostras"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="coincidencia1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="|vi@gra|v1agra|v1@gra|v!@gr@"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="sexo">
          <xs:complexType>
            <xs:sequence>
            <xs:element name="femenino">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(f|F|Mujer|M){0,1}"/>
                </xs:restriction>  
              </xs:simpleType>
            </xs:element>
            <xs:element name="masculino">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(m|M|Hombre|H){0,1}"/>
                </xs:restriction>  
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="atributoSexo"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence> 
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="atributoSexo">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1"/>
      <!-- otra opción-->
      <xs:enumeration value="0|1"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== Manuelrg99/LLMM/Validación/XSD/ejercicios/ejercicios.xml
<?xml version="1.0"?>

<ejercicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ejercicios.xsd">

<numero>+34677121212</numero>
<password>Mrg29</password>
<dni>30101010-A</dni>
<correo>pepe87@gmail.com</correo>
<coincidencia>maldito</coincidencia>
<coincidencia1>v1agra</coincidencia1>
<sexo>
    <femenino>f</femenino>
    <masculino>Hombre</masculino>
</sexo>



<!-- EJERCICIOS
1.-patrón para un número de teléfono como el siguiente
+34677121212


2.- Patrón para poner un password entre 5 y 8 caracteres con mayusculas, minusculas y números

3.- Patrón para el DNI 30101010A

4.- Patron para coincidencia con cualquier palabra o frase de la lista siguiente:
tontería
maldito
caray
caramba
madre mía
ostras

5.- Patron para coincidencia con la palabra "viagra" y con algunas de las alteraciones que utilizan los emisores de spam, por ejemplo:
vi@gra
v1agra
v1@gra
v!@gr@

6.- Patrón para correo electrónico
por ejemplo: pepe87@gmail.com -->

</ejercicios>
