=== Manuelrg99/LLMM/Validación/DTD/notas/notas.dtd
<!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (mensaje, fecha)> <!-- <!ELEMENT body (#PCDATA)> -->
        <!ELEMENT mensaje (#PCDATA)>
        <!ELEMENT fecha (dia, mes, anno)> <!-- <!ELEMENT fecha (#PCDATA)> -->
            <!ELEMENT dia (#PCDATA)>
            <!ELEMENT mes (#PCDATA)>
            <!ELEMENT anno (#PCDATA)>

=== Manuelrg99/LLMM/Validación/DTD/notas/notas.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "notas.dtd">

<note>
    <to>Manuel</to>
    <from>Ra√∫l</from>
    <heading>Recordatorio</heading>
    <body>
        <mensaje>Este es el mensaje</mensaje>
        <fecha>
            <dia>3</dia>
            <mes>Marzo</mes>
            <anno>2022</anno>
        </fecha>
    </body>
</note>
