=== Manuelrg99/LLMM/Validación/DTD/medicamentos/medicamento.dtd
<!ELEMENT Farmacia (medicamento+)>
<!ELEMENT medicamento (Nombre,Administracion,Dosis)>
    <!ELEMENT Nombre (Generico, Comercial+)>
        <!ELEMENT Generico (#PCDATA)>
        <!ELEMENT Comercial (#PCDATA)>
    <!ELEMENT Administracion (#PCDATA)>
    <!ELEMENT Dosis (#PCDATA)>
    
    <!ATTLIST Nombre id CDATA #REQUIRED>
    <!ATTLIST Administracion tipo CDATA #REQUIRED>

=== Manuelrg99/LLMM/Validación/DTD/medicamentos/medicamento.xml
<?xml version="1.0"?>
<!DOCTYPE Farmacia SYSTEM "medicamento.dtd">
<Farmacia>
    <medicamento>
        
        <Nombre id="1">
            <Generico></Generico>
            <Comercial></Comercial>
        </Nombre>

        <Administracion tipo="Intramuscular"></Administracion>
        <Dosis></Dosis>
    </medicamento>
    <medicamento>
        
        <Nombre id="2">
            <Generico>Ra√∫l</Generico>
            <Comercial>Recordatorio</Comercial>
        </Nombre>

        <Administracion tipo="Oral"></Administracion>
        <Dosis></Dosis>
    </medicamento>
</Farmacia>
