=== Manuelrg99/LLMM/Validación/XSD/ejercicioresumen/ejercicioresumen.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="resumenes">
        <xs:complexType>
            <xs:sequence>
                <!--Definimos elementos-->
                <xs:element name="simples">
                    <xs:complexType>
                        <!--Vamos a definir elementos simples-->
                        <xs:all>
                            <!--podemos cambiar el orden de secuencia establecido-->
                            <xs:element name="SinAtributo" type="xs:string"/>
                            <!-- Tipo simple= integer, date, string, etc-->
                            <xs:element name="integer" type="xs:integer"/>
                            <xs:element name="string" type="xs:string"/>
                            <xs:element name="date" type="xs:date"/>
                            <!-- Tipo simple= integer, date, string, etc-->
                            <xs:element name="elementoDefinido" type="elemenDefinido"/>
                            <!--Nos dirigmos al final del documento-->
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <!--Vamos a definir elementos complejos-->
                <xs:element name="ConjuntosComplejos">
                    <xs:complexType>
                        <xs:sequence>
                            <!--Elemnto complejo sin atributo-->
                            <xs:element name="elemento1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elemento1.1" type="xs:string"/>
                                        <xs:element name="elemento1.2" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--Elemnto complejo con atributo-->
                            <xs:element name="elemento2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elemento2.1" type="xs:string"/>
                                        <xs:element name="elemento2.2" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <!--Elemento complejo sin atributo con tipo definido en el elemento simple (se comporta como un cmplextype pero es reutilizable)-->
                            <xs:element name="elemento3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!--Elemnto simple sin atributo Tipo  definido-->
                                        <xs:element name="elemento1.1" type="elemento1.1.1"/>
                                        <xs:element name="elemento1.2" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--Restricciones--><!--Expresiones Regulares Numericas--><!--Patrón para un número de teléfono como el siguiente +34 677 121 212-->
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[+][0-9]{11}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--Expresiones Regulares de Cadenas-->
                            <!--Patron para coincidencia con la palabra "viagra" y con algunas de las alteraciones que utilizan 
                    los emisores de spam, por ejemplo: vi@gra v1agra v1@gra v!@gr@ -->
                            <xs:element name="pastilla">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="viagra|vi@gra|v1agra|v1@gra|v!@gr@"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--Expresiones Regulares Mixtas-->
                            <!--Patrón para correo electrónico por ejemplo: pepe87@gmail.com -->
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[_]*[a-z0-9]{6,50}[@][a-z]{1,10}[.][a-z]{2,6}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--All/Choice /sequence--><!--Secuence obliga a respetar el orden en el que esta en el xsd-->
                            <xs:element name="tarjetas1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="color1" type="xs:string"/>
                                        <xs:element name="color2" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--Choice obliga a tener al menos una de las opciones que esta en el xsd-->
                            <xs:element name="tarjetas2">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="color1" type="xs:string"/>
                                        <xs:element name="color2" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <!--All obliga a que aparezcan todas las opciones pero en el orden que queramos que esta en el xsd-->
                            <xs:element name="tarjetas3">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="color1" type="xs:string"/>
                                        <xs:element name="color2" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <!--max-minoccurs en elemento simple -->
                            <xs:element name="tema" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="curso" minOccurs="1" maxOccurs="10">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="10">
                                        <xs:element name="puesto" type="xs:integer" minOccurs="1" maxOccurs="10"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--Grupos de elementos para reutilizar-->
                            <xs:element name="alumno">
                                <xs:complexType>
                                    <xs:group ref="persona"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="profesor">
                                <xs:complexType>
                                    <xs:group ref="persona"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--########--><!--Definicion del atributo definido simple-->
    <xs:simpleType name="elemenDefinido">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tonteria"/>
            <xs:enumeration value="maldito"/>
            <xs:enumeration value="caray"/>
            <xs:enumeration value="caramba"/>
            <xs:enumeration value="madre"/>
            <xs:enumeration value="mia"/>
            <xs:enumeration value="ostras"/>
        </xs:restriction>
    </xs:simpleType><!--Definicion del atributo definido complejo-->
    <xs:complexType name="elemento1.1.1">
        <xs:sequence>
            <xs:element name="loclaidad" type="xs:string"/>
            <xs:element name="cp" type="xs:string"/><!--apunta el elemento defindo antrerior-->
            <xs:element name="ciudad" type="elemenDefinido"/>
        </xs:sequence>
    </xs:complexType><!--Definicion de grupo-->
    <xs:group name="persona">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="direccion" type="xs:string"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== Manuelrg99/LLMM/Validación/ejercicioresumen/ejercicioresumen.xml
<?xml version="1.0" encoding="UTF-8"?>

<resumenes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicioresumen.xsd">
    <!--Definimos elementos-->
    <simples>
        <!--Vamos a definir elementos simples-->
        <SinAtributo>hola</SinAtributo>
        <!-- Tipo simple= integer, date, string, etc-->
        <integer>10</integer>
        <string>adios</string>
        <date>2022-10-10</date>
        <!-- Tipo simple= integer, date, string, etc-->
        <elementoDefinido>tonteria</elementoDefinido>
    </simples>

    <!--Vamos a definir elementos complejos-->
    <ConjuntosComplejos>
        <!--Elemnto complejo sin atributo-->
        <elemento1>
            <elemento1.1>uno</elemento1.1>
            <elemento1.2>dos</elemento1.2>
        </elemento1>
        <!--Elemnto complejo con atributo-->
        <elemento2 id="uno">
            <elemento2.1>uno</elemento2.1>
            <elemento2.2>dos</elemento2.2>
        </elemento2>
        <!--Elemento complejo sin atributo con tipo definido en el elemento simple (se comporta como un cmplextype pero es reutilizable)-->
        <elemento3>
            <elemento1.1>
                <loclaidad>Ecija</loclaidad>
                <cp>41400</cp>
                <ciudad>tonteria</ciudad>
            </elemento1.1>
            <elemento1.2>adios</elemento1.2>
        </elemento3>

        <!--Restricciones-->
        <!--Expresiones Regulares Numericas-->
        <!--Patrón para un número de teléfono como el siguiente +34 677 121 212-->
        <telefono>+34652236310</telefono>


        <!--Expresiones Regulares de Cadenas-->
        <!--Patron para coincidencia con la palabra "viagra" y con algunas de las alteraciones que utilizan 
            los emisores de spam, por ejemplo: vi@gra v1agra v1@gra v!@gr@ -->
        <pastilla>viagra</pastilla>

        <!--Expresiones Regulares Mixtas-->
        <!--Patrón para correo electrónico por ejemplo: pepe87@gmail.com -->
        <email>juanjoseam1980@gmail.com</email>

        <!--All/Choice /sequence-->
        <!--Secuence obliga a respetar el orden en el que esta en el xsd-->
        <tarjetas1>
            <color1>amarillo</color1>
            <color2>rojo</color2>
        </tarjetas1>

        <!--Choice obliga a tener al menos una de las opciones que esta en el xsd-->
        <tarjetas2>
            <color1>amarilla</color1>
        </tarjetas2>

        <!--All obliga a que aparezcan todas las opciones pero en el orden que queramos que esta en el xsd-->
        <tarjetas3>
            <color2>rojo</color2>
            <color1>amarillo</color1>
        </tarjetas3>

         <!--max-minoccurs en elemento simple -->
        <tema>1</tema>

        <curso>
            <puesto>1</puesto>
            <puesto>2</puesto>
        </curso>


        <!--Grupos de elementos para reutilizar-->
        <alumno>
            <nombre>Juan</nombre>
            <apellidos>Arroyo</apellidos>
            <direccion>Calle 1</direccion>
        </alumno>

        <profesor>
            <nombre>Angela</nombre>
            <apellidos>Rider</apellidos>
            <direccion>Calle 2</direccion>
        </profesor>
    </ConjuntosComplejos>
</resumenes>
