=== Manuelrg99/LLMM/Validación/recuperacion/recuperacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aeropuertos">
        <xs:complexType>
            <xs:sequence><!-- sequence, porque nos pide que sea en el orden que nos indica el 
                enunciado y por eso lo colocamos de la siguiente forma los element de dentro de 
                la secuencia-->
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="vuelos">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="vuelo" minOccurs="1" maxOccurs="unbounded">
                                    <!-- Como el enunciado nos pide como obligatorio un vuelo como 
                                        mínimo añadimos minOccurs="1" y como puede haber infinitos 
                                    vuelos, añadimos maxOccurs="unbounded"-->
                                    <xs:complexType>
                                        <xs:sequence><!-- sequence, porque nos pide que aparezca en el  
                                            orden que aparece en el panel que nos indica el enunciado y 
                                            por eso lo colocamos de la siguiente forma los element de dentro de la 
                                            secuencia-->
                                            <xs:element name="diario" minOccurs="0"/> <!-- minOccurs="0" porque se puede no poner la etiqueta diario-->
                                            <xs:element name="origen" type="Origendefinido"/> <!-- "type" Para definirlo más tarde-->
                                            <xs:element name="destino" type="Destinodefinido"/> <!-- "type" Para definirlo más tarde-->
                                            <xs:element name="hora">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="hora-salida" type="horadefinida"/> <!-- "type" Para definirlo más tarde-->
                                                        <xs:element name="hora-embarque" type="Horadefinida"/> <!-- "type" Para definirlo más tarde-->
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="puerta-embarque" type="xs:string"/> <!-- "type" Para definirlo más tarde-->
                                            <xs:element name="observaciones" type="xs:string"/> <!-- "type" Para definirlo más tarde-->
                                        </xs:sequence>
                                        <xs:attribute name="código">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:ID"><!-- xs:ID, para ponerlo como único el código-->
                                                    <xs:pattern value="[A-Z]{2,3}"/> <!-- Para ponerle la restricción al código-->
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="estado" default="E"> <!-- Para ponerle por defecto "E"-->
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[CER]"/><!-- Para ponerle el valor que puede coger el estado-->
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="fecha-panel" type="xs:date"/>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="vuelos">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="vuelo" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="diario" minOccurs="0"/>
                                            <xs:element name="origen" type="Origendefinido"/>
                                            <xs:element name="destino" type="Destinodefinido"/>
                                            <xs:element name="hora">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="hora-salida" type="horadefinida"/>
                                                        <xs:element name="hora-embarque" type="Horadefinida"/>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="puerta-embarque" type="xs:string"/>
                                            <xs:element name="observaciones" type="xs:string"/>
                                        </xs:sequence>
                                        <xs:attribute name="código">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:ID">
                                                    <xs:pattern value="[A-Z]{2,3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="estado" default="E">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[CER]"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="fecha-panel" type="xs:date"/>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="vuelos">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="vuelo" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="diario" minOccurs="0"/>
                                            <xs:element name="origen" type="Origendefinido"/>
                                            <xs:element name="destino" type="Destinodefinido"/>
                                            <xs:element name="hora">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="hora-salida" type="horadefinida"/>
                                                        <xs:element name="hora-embarque" type="Horadefinida"/>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="puerta-embarque" type="xs:string"/>
                                            <xs:element name="observaciones" type="xs:string"/>
                                        </xs:sequence>
                                        <xs:attribute name="código">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:ID">
                                                    <xs:pattern value="[A-Z]{2,3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="estado" default="E">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[CER]"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="fecha-panel" type="xs:date"/><!-- Para ponerle el tipo al elemento fecha-panel-->    
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <!-- REFERENCIAS -->

    <xs:simpleType name="Origendefinido">
        <xs:restriction base="xs:string">
            <!--<xs:pattern value="([A-Z]{1,3})"/>--><!-- Podríamos añadir este valor para escribir las 3 primeras letras de otra provincia si fuese necesario -->
            <xs:pattern value="SEV|MAL|MAD"/> <!-- Valores que coge la restricción-->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Destinodefinido">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]{1,20})"/> <!-- Valores que coge la restricción para el destino-->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="horadefinida">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-2][0-9][:][0-5][0-9])*"/> <!-- Valores que coge la restricción para la hora -->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Horadefinida">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-2][0-9][:][0-5][0-9])*"/> <!-- Valores que coge la restricción para la hora -->
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== Manuelrg99/LLMM/Validación/recuperacion/recuperacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuertos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="recuperacion.xsd">
            <nombre>Sevilla</nombre><!-- Nombre del aeropuerto-->

            <vuelos><!-- Etiqueta para agrupar los vuelos de un aeropuerto-->

                <vuelo código="DLH" estado="R"><!-- Etiqueta que agrupa los datos del vuelo y tiene como atributo el codigo del vuelo y el estado del vuelo -->
                    <diario/><!-- Etiqueta que puede aparecer o no, para indicar si el vuelo es diario o no-->
                    <origen>SEV</origen> <!-- Origen del vuelo-->
                    <destino>Munich</destino> <!-- Destino del vuelo-->
                    <hora><!-- Etiqueta creada para agrupar las horas de salida y embarque-->
                        <hora-salida>15:45</hora-salida> <!-- Etiqueta para la hora de salida-->
                        <hora-embarque>15:41</hora-embarque><!-- Etiqueta para la hora de embarque-->
                    </hora>
                    <puerta-embarque>D68</puerta-embarque><!-- Etiqueta para la puerta de embarque-->
                    <observaciones>ESTIMA. 16:11h</observaciones><!-- Etiqueta para las observaciones-->
                </vuelo>

                <vuelo código="IBE" estado="E">
                    <diario>SI</diario>
                    <origen>SEV</origen>
                    <destino>Barcelona</destino>
                    <hora>
                        <hora-salida>15:50</hora-salida>
                        <hora-embarque>15:40</hora-embarque>
                    </hora>
                    <puerta-embarque>D65</puerta-embarque>
                    <observaciones>EMBARQUE</observaciones>    
                </vuelo>
                <vuelo código="IBE" estado="E"> <!-- Esta etiqueta da error porque como tenemos 
                    que poner el código como único y hay dos códigos repetidos -->
                    <diario>SI</diario>
                    <origen>SEV</origen>
                    <destino>Bilbao</destino>
                    <hora>
                        <hora-salida>15:50</hora-salida>
                        <hora-embarque>15:40</hora-embarque>
                    </hora>
                    <puerta-embarque>D44</puerta-embarque>
                    <observaciones>EMBARQUE</observaciones>    
                </vuelo>
                <vuelo código="VLG" estado="R">
                    <diario>SI</diario>
                    <origen>SEV</origen>
                    <destino>Madrid</destino>
                    <hora>
                        <hora-salida>15:35</hora-salida>
                        <hora-embarque>15:25</hora-embarque>
                    </hora>
                    <puerta-embarque>B18</puerta-embarque>
                    <observaciones>IR A PTA</observaciones>    
                </vuelo>
            </vuelos>
            <fecha-panel>2022-08-21</fecha-panel><!-- Fecha del panel, no sé a qué fecha se refiere 
            el enunciado del trabajo, por lo tanto que puedo una fecha al azar -->

            <nombre>Madrid</nombre>
            <vuelos>
                <vuelo código="VLG" estado="E"> <!-- Esta etiqueta da error porque como tenemos 
                    que poner el código como único y hay dos códigos repetidos -->
                    <diario/>
                    <origen>MAD</origen>
                    <destino>Emiratos</destino>
                    <hora>
                        <hora-salida>16:40</hora-salida>
                        <hora-embarque>16:00</hora-embarque>
                    </hora>
                    <puerta-embarque>C33</puerta-embarque>
                    <observaciones>ENLACE D46 Procedente de Madrid</observaciones>    
                </vuelo>
                <vuelo código="AEA" estado="C">
                    <diario/>
                    <origen>MAD</origen>
                    <destino>Malaga</destino>
                    <hora>
                        <hora-salida>16:15</hora-salida>
                        <hora-embarque></hora-embarque>
                    </hora>
                    <puerta-embarque>D61</puerta-embarque>
                    <observaciones>ESTIMA. 16:11h</observaciones>    
                </vuelo>
            </vuelos>
            <fecha-panel>2022-08-21</fecha-panel>

            <nombre>Málaga</nombre>
            <vuelos>
                <vuelo código="DB" estado="E">
                    <diario/>
                    <origen>MAL</origen>
                    <destino>Melilla</destino>
                    <hora>
                        <hora-salida>15:30</hora-salida>
                        <hora-embarque>15:25</hora-embarque>
                    </hora>
                    <puerta-embarque>B15</puerta-embarque>
                    <observaciones>EMBARQUE CERRADO</observaciones>    
                </vuelo>
            </vuelos>
            <fecha-panel>2022-08-21</fecha-panel>
</aeropuertos>
